"use client";

import { Baby, ListPlus, Building2, CircleParking, Coffee, Fuel, GraduationCap, Hospital, Hotel, Landmark, MapPin, Pill, School, ShoppingBasket, Store, Theater, TrainFront, Utensils, X, type LucideIcon } from "lucide-react";
import { FormEvent, useEffect, useRef, useState } from "react";
import type { Place } from "@/features/route-optimization/types/route.types";

type SearchResult = Omit<Place, "id" | "type"> & { categoryName?: string; categoryGroupCode?: string; categoryGroupName?: string; };
type Feedback = "idle" | "not-found" | "error";
const CATEGORY_ICONS: Record<string, LucideIcon> = { MT1: ShoppingBasket, CS2: Store, PS3: Baby, SC4: School, AC5: GraduationCap, PK6: CircleParking, OL7: Fuel, SW8: TrainFront, BK9: Landmark, CT1: Theater, AG2: Building2, PO3: Building2, AT4: Landmark, AD5: Hotel, FD6: Utensils, CE7: Coffee, HP8: Hospital, PM9: Pill };
function CategoryIcon({ code }: { code?: string }) { const Icon = CATEGORY_ICONS[code ?? ""] ?? MapPin; return <Icon className="search-result-category-icon" aria-hidden="true" />; }

export function LocationSearch({ onAdd, onSave }: { onAdd: (place: SearchResult) => void; onSave?: (place: SearchResult) => void }) {
  const [query, setQuery] = useState(""); const [results, setResults] = useState<SearchResult[]>([]); const [loading, setLoading] = useState(false); const [hasSearched, setHasSearched] = useState(false); const [feedback, setFeedback] = useState<Feedback>("idle"); const [isExpanded, setExpanded] = useState(false);
  const abortRef = useRef<AbortController | null>(null); const feedbackTimerRef = useRef<number | null>(null);
  function showFeedback(type: Exclude<Feedback, "idle">) { if (feedbackTimerRef.current) window.clearTimeout(feedbackTimerRef.current); setFeedback(type); navigator.vibrate?.(type === "not-found" ? [8, 24, 8] : 18); feedbackTimerRef.current = window.setTimeout(() => setFeedback("idle"), 720); }
  function clearSearch() { abortRef.current?.abort(); setQuery(""); setResults([]); setLoading(false); setHasSearched(false); setFeedback("idle"); setExpanded(false); }
  function choose(place: SearchResult) { onAdd(place); clearSearch(); }
  useEffect(() => { const term = query.trim(); abortRef.current?.abort(); if (term.length < 2) { setResults([]); setLoading(false); setHasSearched(false); setFeedback("idle"); return; } setHasSearched(false); setFeedback("idle"); const controller = new AbortController(); abortRef.current = controller; const timer = window.setTimeout(async () => { setLoading(true); try { const response = await fetch(`/api/places/search?query=${encodeURIComponent(term)}`, { signal: controller.signal }); const body = await response.json() as { results?: SearchResult[]; error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message || "장소 검색에 실패했습니다."); const next = (body.results ?? []).slice(0, 5); setResults(next); setHasSearched(true); if (!next.length) showFeedback("not-found"); } catch (error) { if (error instanceof DOMException && error.name === "AbortError") return; setResults([]); setHasSearched(false); showFeedback("error"); } finally { if (!controller.signal.aborted) setLoading(false); } }, 100); return () => { window.clearTimeout(timer); controller.abort(); }; }, [query]);
  useEffect(() => () => { if (feedbackTimerRef.current) window.clearTimeout(feedbackTimerRef.current); }, []);
  function submit(event: FormEvent) { event.preventDefault(); if (results[0]) choose(results[0]); else if (query.trim().length >= 2 && !loading) showFeedback(hasSearched ? "not-found" : "error"); }
  return <form onSubmit={submit} className={`search-form naver-search-form${isExpanded || query ? " search-expanded" : ""}`}><label className="sr-only" htmlFor="search">장소 또는 주소 검색</label><div className="search-control"><div className={`search-input-row ${feedback !== "idle" ? `search-feedback ${feedback}` : ""}`}><input id="search" value={query} onFocus={() => setExpanded(true)} onBlur={() => { if (!query.trim()) setExpanded(false); }} onChange={(event) => { setQuery(event.target.value); if (event.target.value) setExpanded(true); }} placeholder="장소, 주소 검색" autoComplete="off" aria-expanded={results.length > 0} aria-controls="place-search-results" />{query && <button className="search-clear" type="button" aria-label="검색어 지우기" onClick={clearSearch}><X size={16} /></button>}</div>{results.length > 0 && <ul id="place-search-results" className="search-results" role="listbox">{results.map((place, index) => <li key={`${place.name}-${place.latitude}-${place.longitude}`} role="option" aria-selected={index === 0}><button type="button" className="search-result-add" onClick={() => choose(place)}><CategoryIcon code={place.categoryGroupCode} /><span><strong>{place.name}</strong><small>{place.address || `${place.latitude.toFixed(5)}, ${place.longitude.toFixed(5)}`}</small></span></button>{onSave && <button type="button" className="search-result-save" onClick={() => onSave(place)} aria-label={`${place.name} 장소 리스트에 저장`}><ListPlus size={16} /></button>}</li>)}</ul>}</div></form>;
}