"use client";

import { Check, ChevronLeft, MapPinPlus, Plus, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { LIST_COLORS, type MemberPlaceList, type SavedPlace } from "@/features/member/types";

interface Props { lists: MemberPlaceList[]; activeList: MemberPlaceList | null; places: SavedPlace[]; onBack: () => void; onSelect: (id: string) => void; onCreate: (name: string, color: string) => void; onUpdate: (id: string, name: string, color: string) => void; onDeleteList: (id: string) => void; onDeletePlace: (id: string) => void; onAddToRoute: (place: SavedPlace) => void; }
export function SavedPlacesPanel({ lists, activeList, places, onBack, onSelect, onCreate, onUpdate, onDeleteList, onDeletePlace, onAddToRoute }: Props) {
  const [newName, setNewName] = useState(""); const [newColor, setNewColor] = useState<string>(LIST_COLORS[0]);
  const [editName, setEditName] = useState(""); const [editColor, setEditColor] = useState<string>(LIST_COLORS[0]);
  useEffect(() => { setEditName(activeList?.name ?? ""); setEditColor(activeList?.color ?? LIST_COLORS[0]); }, [activeList?.id, activeList?.name, activeList?.color]);
  if (activeList) return <section className="saved-places-panel"><div className="member-panel-top"><button className="icon-only" type="button" onClick={onBack} aria-label="내 장소 목록으로"><ChevronLeft size={18} /></button><div><p className="eyebrow">내 장소</p><h2>{activeList.name}</h2></div><button className="icon-only danger" type="button" onClick={() => onDeleteList(activeList.id)} aria-label="리스트 삭제"><Trash2 size={17} /></button></div><form className="list-edit-row" onSubmit={(event) => { event.preventDefault(); if (editName.trim()) onUpdate(activeList.id, editName, editColor); }}><input value={editName} onChange={(event) => setEditName(event.target.value)} aria-label="리스트 이름" /><ColorPicker value={editColor} onChange={setEditColor} /><button type="submit" aria-label="리스트 변경 저장"><Check size={16} /></button></form><p className="member-count">저장 장소 {places.length} / 100</p><ol className="saved-place-list">{places.map((place) => <li key={place.id}><div><strong>{place.name}</strong><small>{place.address || `${place.latitude.toFixed(5)}, ${place.longitude.toFixed(5)}`}</small></div><div className="saved-place-actions"><button type="button" onClick={() => onAddToRoute(place)} title="현재 동선에 추가"><MapPinPlus size={16} /></button><button type="button" onClick={() => onDeletePlace(place.id)} title="저장 장소 삭제"><Trash2 size={16} /></button></div></li>)}</ol>{places.length === 0 && <p className="muted">검색 결과나 방문 장소에서 저장한 장소가 여기에 표시됩니다.</p>}</section>;
  return <section className="saved-places-panel"><div className="member-panel-top"><button className="icon-only" type="button" onClick={onBack} aria-label="방문 장소로"><ChevronLeft size={18} /></button><div><p className="eyebrow">내 장소</p><h2>장소 리스트</h2></div></div><form className="new-list-form" onSubmit={(event) => { event.preventDefault(); if (!newName.trim()) return; onCreate(newName, newColor); setNewName(""); }}><input value={newName} onChange={(event) => setNewName(event.target.value)} maxLength={60} placeholder="새 리스트 이름" /><ColorPicker value={newColor} onChange={setNewColor} /><button type="submit" aria-label="새 리스트 생성"><Plus size={17} /></button></form><p className="member-count">리스트 {lists.length} / 50</p><ol className="place-list-cards">{lists.map((list) => <li key={list.id}><button type="button" className="place-list-card" onClick={() => onSelect(list.id)}><span className="list-color-dot" style={{ backgroundColor: list.color }} /><span><strong>{list.name}</strong><small>{list.placeCount}개 장소</small></span><span className="list-card-arrow">›</span></button></li>)}</ol></section>;
}
function ColorPicker({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <div className="list-color-picker" aria-label="리스트 색상">{LIST_COLORS.map((color) => <button key={color} type="button" className={value === color ? "selected" : ""} style={{ backgroundColor: color }} onClick={() => onChange(color)} aria-label={`${color} 색상`} />)}</div>; }